dataforgoodfr/13_potentiel_solaire

.github/pull_request_template.md, CONTRIBUTING.md, README.md
- Nocodb : pas de tâche liée
Cette PR a pour objectif de lister les bonnes pratiques pour faciliter la collaboration sur le projet.
Rien à tester !
=> ajout doc sur les bonnes pratiques pour faciliter la collaboration

algorithme/README.md, algorithme/data/README.md
Nocodb : https://noco.services.dataforgood.fr/dashboard/#/nc/p0dx3u4rkk0ymxl/m8e3rjp5dj2gf5m/Kanban?rowId=5
L'installation via poetry n'était pas tout à fait juste.
Suivre les étapes listées dans algorithme/README.md.
=> maj doc installation de l'env avec poetry

application/README.md
Nocodb : N/A
Issue : https://github.com/dataforgoodfr/13_potentiel_solaire/issues/18
Cette PR a pour objectif de fournir un README pour installer l'environnement de dev pour la partie application.
=> feat: amelioration readme application (#18)

algorithme/notebooks/pipeline_algorithme.ipynb, algorithme/potentiel_solaire/sources/bd_pci.py, algorithme/potentiel_solaire/sources/bd_topo.py, algorithme/potentiel_solaire/sources/utils.py
Cette PR a pour objectif de fix l'issue  #47. 
[Si deja telecharge] Supprimer de /data le folder contentant la donnee PCI
Relancer la pipeline de test
Verifier que la bd PCI a bien été extraite et stockée dans /data
=> Ajout extraction de la bd pci à la pipeline

algorithme/notebooks/analyse_qualite_resultats_pipeline.ipynb
Github issue : [_insérer le lien vers l'issue github correspondante_](https://github.com/dataforgoodfr/13_potentiel_solaire/issues/74)
Cette PR a pour objectif d'analyser les resultats de l'algorithme
Documentation outline : https://outline.services.dataforgood.fr/doc/revue-qualite-algorithme-v0-FqrVMLuB7F
Executer le notebook notebooks/analyse_qualite_resultats_pipeline.ipynb
- J'ai ajouté des commentaires dans le code qui expliquent **pourquoi** certaines …
=> ajout analyses des resultats de l'algorithme

algorithme/notebooks/wns_hauteur.ipynb, algorithme/potentiel_solaire/features/roof_attributes.py
Github issue : https://github.com/dataforgoodfr/13_potentiel_solaire/issues/77
Cette PR a pour objectif de proposer des modifications à la PR https://github.com/dataforgoodfr/13_potentiel_solaire/pull/61
Modifications effectuées :
- renommages
- erreur raise si le CRS de la zone d'intérêt n'est pas en lambert
Appliquer la fonction sur un des bâtiments de la gdf schools_buildings (qu'il faut reprojeter en lambert d'abord)
- J'ai ajouté des commentaires dans le code …
=> Proposition de modifications pour la PR sur l'intégration de fonctions de recupération de données MNS / MNT

application/.env.template, application/.gitignore, application/README.md, application/app/lib/duckdb.ts, application/app/models/communes.ts, application/app/models/departements.ts, application/app/models/regions.ts, application/database/export-geojson.sql, application/database/prepare-JDD-test.sql
Github issue : N/A
Cette PR a pour objectif d'améliorer la configuration à la base de donnée (#54) en utilisant une variable d'environnement.
Le fichier gitignore exclue également la base de donnée duckdb et les gros fichiers geojson qui seront générés sur les environnements des devs.
Avant ce merge, il fallait placer le fichier dans le sous-répertoire du projet avec un nom spécifique `application/database/data-test.duckdb`
Après ce merge il faudra ajouter sur un fichier `.env` en local le chemin **absolu** de la base de donnée duckdb.
```env
// fichier .env.local
DATABASE_PATH=/path/to/my-wonderful-db.duckdb
```
- `npm run dev` : lance le serveur sur le port 3000
- `curl --request GET \
--url 'http://localhost:3000/api/get-communes?codeDepartement=33'` : lance une requête http et vérifie …
=> [FRONT] feat: use env for database file config + split sql

algorithme/README.md
Simplement une petite update du readme pour ne pas que les nouveaux utilisateurs se trompent avec le setup de poetry (ne marche pas avec poetry == 2.1.2)
=> Update readme to install poetry 1.7

application/database/prepare-JDD-test.sql
Github issue : #85 
Cette PR a pour objectif de corriger le script `prepare-JDD-test.sql`.
Executer la partie "[Installer la base de test](https://github.com/dataforgoodfr/13_potentiel_solaire/blob/main/application/README.md#installer-la-base-de-test)" du README (application) sur un nouvel environnement (ex: codespace github). La base de donnée doit être créé avec succès.
Closes #85
=> fix: ensure duckdb extensions are installed + use default schema (#85)

.github/pull_request_template.md, application/README.md
Github issue : N/A
Cette PR a pour objectif :
- d'ajouter quelques bonnes pratiques de code affiché dans le template des pull request.
- de mettre à jour l README application pour l'installation de l'éditeur de code et du formatteur et autres extensions.
=> [FRONT] feat: update section bonnes pratiques

application/app/Providers.tsx, application/app/components/Error.tsx, application/app/components/Map/MapWithLoader.tsx, application/app/layout.tsx, application/app/utils/fetchers/fetchCommunesGeoJSON.ts, application/app/utils/fetchers/fetchEtablissementsGeoJSON.ts, application/app/utils/hooks/useCommunesGeoJSON.ts, application/app/utils/hooks/useEtablissementsGeoJSON.ts, application/package-lock.json, application/package.json
Github issue : https://github.com/dataforgoodfr/13_potentiel_solaire/issues/123
Cette PR a pour objectif d ajouter SWR pour gerer les caching des requetes.
npm i (pour installer swr)
- [ x] J'ai pris connaissance et respecté les [règles de contribution](../CONTRIBUTING.md)
- [ x] Les pre-commit passent
- [ x] Les test unitaires passent
- [ x] Le code modifié fonctionne en local
- [ x] J'ai demandé une peer-review à un autre bénévole du projet
=> [FRONT] feat: add SWR for geojsons fetching

algorithme/notebooks/pipeline_algorithme.ipynb, algorithme/potentiel_solaire/features/pvgis_api.py, algorithme/potentiel_solaire/features/solar_potential.py
Github issue : https://github.com/dataforgoodfr/13_potentiel_solaire/issues/112
Cette PR a pour objectif de résoudre le problème d'absence de réponse de l'API pvigs. Le code va maintenant itérer dans les bâtiments les plus proches du centre si l'API ne renvoie pas de valeur
ll est possible de tester en essayant le département 973 (Guyanne) ou le 93
=> Cherche le premier bâtiment pour lequel l'API pvgis donne une réponse

.github/workflows/ci-algorithme.yaml, algorithme/.pre-commit-config.yaml
Cette PR a pour objectif de fix l'action github pre-commit
=> [ALGO] Fix pre-commit action

application/app/components/Map/constants.ts
Github issue : N/A
Cette PR a pour objectif de corriger le seuil du potentiel des établissements.
=> fix: update seuil for etablissement

.github/workflows/ci-app.yaml
Cette PR a pour objectif d'éviter de build une nouvelle image de l'app à la création d'une PR.
=> Avoid building app on PR

application/app/components/SearchBar/SearchBar.tsx, application/app/components/SearchBar/Suggestions.tsx, application/app/lib/data.ts, application/app/lib/db-mapping/searchView.ts, application/app/models/search.ts
Github issue : [217](https://github.com/dataforgoodfr/13_potentiel_solaire/issues/217)
Cette PR a pour objectif d ajouter le code postal dans la search bar pour les commuens.
- J'ai ajouté des commentaires dans le code qui expliquent **pourquoi** certaines opérations sont faites
- Les noms des fonctions & variables aident à la lecture et compréhension du code
- J'évite des fonctions qui prennent en …
=> [FRONT] feat: add code postal in search bar 

application/app/lib/data.ts
Github issue : [_240_](https://github.com/dataforgoodfr/13_potentiel_solaire/issues/240)
Cette PR a pour objectif d'augmenter le nombre de résultats retournés à 20
- J'ai ajouté des commentaires dans le code qui expliquent **pourquoi** certaines opérations sont faites
- Les noms des fonctions & variables aident à la lecture et compréhension du code
- J'évite des fonctions qui prennent en argument des …
=> chore: extend search suggestions display

application/app/components/fiches/ficheCommune.tsx, application/app/components/fiches/ficheDepartement.tsx, application/app/components/fiches/ficheRegion.tsx, application/app/components/fiches/shared/RepartitionPotentielSolaire.tsx
Github issue : _[240](https://github.com/dataforgoodfr/13_potentiel_solaire/issues/240)_
Cette PR a pour objectif de fixer les fiches zones d'après les retours des bêta testeurs.
> sur la répartition des potentiels (ng etablissements par niveau), on doit afficher potentiel solaire "limité" plutôt que de potentiel "bas"
> 
> remplacer toggle "Tous" par "Tous types"
- J'ai ajouté des commentaires dans le …
=> fix: fiches zones correction post beta test

application/app/components/NavBar.tsx, application/app/layout.tsx
Github issue : #276 
Cette PR a pour objectif de _à renseigner_
- J'ai ajouté des commentaires dans le code qui expliquent **pourquoi** certaines opérations sont faites
- Les noms des fonctions & variables aident à la lecture et compréhension du code
- J'évite des fonctions qui prennent en argument des dataframes et renvoient celles-ci modifiées
- J'écrit des tests unitaires pour les fonctions les plus …
=> fix de navbar et tag en double

application/mock/Dockerfile, application/package-lock.json, application/package.json
Github issue : N/A
Cette PR a pour objectif de mettre à jour les packages avec les derniers patchs + utiliser la dernière version du client node duckdb.
N/A
=> chore: bump lib patch versions + duckdb node api

application/app/components/Footer.tsx, application/app/components/content/footer.ts
Github issue : _#316_
Cette PR a pour objectif de rendre les liens du footer plus facilement accessible;
- Je m'assure que mon code est à jour par rapport à la branche `main` pour tester avec la dernière version du code
- Le linter ne remonte pas d'erreur : `npm run lint`
- J'évite d'utiliser le type `any`
=> [FRONT] Fix footer text size

application/app/components/NavBar.tsx
Github issue : _#315_
Cette PR a pour objectif de rendre visible la page du menu sur laquelle ce trouve l'utilisateur
- Je m'assure que mon code est à jour par rapport à la branche `main` pour tester avec la dernière version du code
- Le linter ne remonte pas d'erreur : `npm run lint`
- J'évite d'utiliser le type `any`
=> [FRONT] Show active menu page

application/app/components/fiches/ficheRegion.tsx
Github issue : #342 
Cette PR a pour objectif de corriger le libellé tous etablissement sur la répartition des établissements de la fiche région.
=> fix: update region tous type repartition libelle

application/app/components/fiches/ficheEtablissement/ficheEtablissement.tsx
Github issue : #218 
Cette PR a pour objectif de corriger la modification amenée par la PR #346  
N/A
=> fix: update last component

application/app/components/Map/FranceMap.tsx, application/app/components/NavBar.tsx
Cette PR a pour objectif de régler les quelques issues qui ont été signalées sur la fonctionnalité impression version mobile
- Je m'assure que mon code est à jour par rapport à la branche `main` pour tester avec la dernière version du code
- Le linter ne remonte pas d'erreur : `npm run lint`
- J'évite d'utiliser le type `any`
=> [FRONT] Fix print feature for mobile
